theme: jekyll-theme-dinky
title: SpecGuru Project - Inferring Software Specifications from Open Source Repositories by Leveraging Data and Collective Community Expertise
description: Inferring Software Specifications from Open Source Repositories by Leveraging Data and Collective Community Expertise
